version: "3.3"
services:
  api:
    build:
      context: ./../API
      dockerfile: ./Dockerfile
    image: faction/api:local
    environment:
      - API_UPLOAD_DIR=/opt/faction/uploads
      - FLASK_SECRET=changemehunter2
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=faction
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=changemehunter2
      - POSTGRES_INIT_ON_START=1
      - RABBIT_HOST=mq
      - RABBIT_USERNAME=guest
      - RABBIT_PASSWORD=changemehunter2
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      factionpub:
    volumes:
      - ./../API/apis:/app/apis
      - ./../API/backend:/app/backend
      - ./../API/logger:/app/logger
      - ./../API/models:/app/models
      - ./../API/processing:/app/processing
      - ./../API/app.py:/app/app.py
      - ./../API/config.py:/app/config.py
      # - ./../API/Pipfile:/app/Pipfile
      # - ./../API/Pipfile.lock:/app/Pipfile.lock
      - ./../API/docker_build/logging.conf:/app/logging.conf
  console:
    build:
      context: ./../Console
      dockerfile: ./Dockerfile
    image: faction/console:local
    ports:
      - "127.0.0.1:80:80"
    networks:
      factionpub:
    volumes:
      - ./../Console/dist:/var/www
      - ./../Console/docker_build/nginx.insecure.conf:/etc/nginx/nginx.conf

  mq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=changemehunter2
    networks:
      factionpub:
    logging:
      driver: none
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=faction
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changemehunter2
    networks:
      factionpub:
    logging:
      driver: none
  # dbui:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=postgres
  #     - PGADMIN_DEFAULT_PASSWORD=changemehunter2
  #     - PGADMIN_LISTEN_PORT=8888
  #   ports:
  #     - "127.0.0.1:8888:8888"
  #   networks:
  #     factionpub:
  #   logging:
  #     driver: none

networks:
  factionpub:
    # Use a custom driver
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.30.0/24
    driver_opts:
      com.docker.network.bridge.name: factionpub0
